# Generated by Django 4.2.3 on 2023-11-17 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('taken', 'Taken')], default='available'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(verbose_name=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')])),
                ('book_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed', to='book.bookinstance')),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
