# Generated by Django 4.2.3 on 2023-11-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookinstance_status_borrowedbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstancephoto',
            old_name='book',
            new_name='book_instance',
        ),
    ]
