# Generated by Django 4.2.3 on 2023-11-19 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_rename_bookinstancephoto_bookphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='new'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(default='3rd ed', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('uzbek', 'Uzbek'), ('russian', 'Russian'), ('english', 'English'), ('tajik', 'Tajik')], default='english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='shared_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('taken', 'Taken')], default='available'),
            preserve_default=False,
        ),
    ]
