# Generated by Django 4.2.3 on 2023-12-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_bookrequest_duration_borrowedbook_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='duration',
        ),
    ]
