# Generated by Django 4.2.3 on 2023-12-04 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_remove_bookrequest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='duration',
            field=models.DateField(default=datetime.datetime(2023, 12, 4, 9, 46, 1, 522593, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
