# Generated by Django 4.2.3 on 2023-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_remove_bookrequest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='duration',
            field=models.PositiveIntegerField(default=14),
            preserve_default=False,
        ),
    ]
