version: '3.10'

services:
  web:
      build: .
      command: /bin/sh -c "sleep 3 && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./:/usr/src/app/
      ports:
        - 8000:8000
      env_file:
        - ./.env
      depends_on:
        - db
  db:
    image: postgres:12-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data: