# Generated by Django 4.2.3 on 2023-11-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_book_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
