# Generated by Django 4.2.3 on 2023-11-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_name_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='telegram_photo_id',
            field=models.CharField(null=True),
        ),
    ]
