# Generated by Django 4.2.3 on 2023-12-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_borrowedbook_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='duration',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='duration',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='status',
            field=models.CharField(verbose_name=[('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Overdue', 'Overdue')]),
        ),
    ]
