# Generated by Django 4.2.3 on 2023-12-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_alter_book_cover_photo_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='telegram_photo_id',
            field=models.CharField(default='AgACAgIAAxkBAAId0GWFz38QapaHL7gWJL5sM3qPEm', null=True),
        ),
    ]
