# Generated by Django 4.2.3 on 2023-12-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_alter_book_telegram_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='telegram_photo_id',
            field=models.CharField(default='AgACAgIAAxkBAAId0GWFz38QapaHL7gWJL5sM3qPEm-IAAKj1TEboKkxSKyRW1W9vrvsAQADAgADbQADMwQ', null=True),
        ),
    ]
