# Generated by Django 4.2.3 on 2023-12-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_telegram_user_id_alter_user_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
    ]
