# Generated by Django 4.2.3 on 2023-11-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(default='@default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='901515484', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
