# Generated by Django 4.2.3 on 2023-11-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_profile_picture_user_telegram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
